### PR TITLE
Update from 7.2.4 to 7.2.5

### PR DESCRIPTION
**Pull request by Biscuiterie975**

### CODE REVIEW

**Comment by intoeetive** [comment]
@Biscuiterie975 Thank you for contributing!
I changed the base to `7.x` (which is the correct base for EE7, not `master`), but it shows too many changed files, plus some conflicts to resolve. 
I think something might be not 100% right with your commits, could you please check?

**Comment by Biscuiterie975** [comment]
***@***.*** Thank you for contributing!
<br/>I changed the base to `7.x` (which is the correct base for EE7, not `master`), but it shows too many changed files, plus some conflicts to resolve. 
<br/>I think something might be not 100% right with your commits, could you please check?
<br/>
<br/>-- 
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/EllisLab/EE-Language-French/pull/58#issuecomment-1362854432
<br/>You are receiving this because you were mentioned.
<br/>
<br/>Message ID: ***@***.***&gt;</div>

**Comment by Biscuiterie975** [comment]
***@***.*** Thank you for contributing!
<br/>&lt;br/&gt;I changed the base to `7.x` (which is the correct base for EE7, not `master`), but it shows too many changed files, plus some conflicts to resolve. 
<br/>&lt;br/&gt;I think something might be not 100% right with your commits, could you please check?
<br/>&lt;br/&gt;
<br/>&lt;br/&gt;-- 
<br/>&lt;br/&gt;Reply to this email directly or view it on GitHub:
<br/>&lt;br/&gt;https://github.com/EllisLab/EE-Language-French/pull/58#issuecomment-1362854432
<br/>&lt;br/&gt;You are receiving this because you were mentioned.
<br/>&lt;br/&gt;
<br/>&lt;br/&gt;Message ID: ***@***.***&amp;gt;&lt;/div&gt;</div>

**Comment by Biscuiterie975** [comment]
***@***.*** Thank you for contributing!
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;I changed the base to `7.x` (which is the correct base for EE7, not `master`), but it shows too many changed files, plus some conflicts to resolve. 
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;I think something might be not 100% right with your commits, could you please check?
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;-- 
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;Reply to this email directly or view it on GitHub:
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;https://github.com/EllisLab/EE-Language-French/pull/58#issuecomment-1362854432
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;You are receiving this because you were mentioned.
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;Message ID: ***@***.***&amp;amp;gt;&amp;lt;/div&amp;gt;&lt;/div&gt;</div>

**Review by intoeetive — CHANGES_REQUESTED** [review]
@Biscuiterie975 upon further look I see that most of the changes are removing 5.x files, so might be correct.

I would like to ask you to NOT make some changes though:
- please keep `.editorconfig` and `.gitignore` files
- please do not just delete content from README file - the information on previous editors is important to have

I am also going to close your other PR, as it seems to be containing all the same changes. Let's stick to this one.

**Pull request closed without merging**
