### PR TITLE
Fixed error in the pro_search_lang.php file  French language 7.2.6

### PR DESCRIPTION
**Pull request by Biscuiterie975**
I have fixed an error (an unwanted period which appeared lign 155 and caused a script warning in the CP while attempting to reach the add-on page). 

I don't use the cli_lang.php myself and this file has had many changes in the two last versions. Can you check for any errors? I did read the latter a few times  but cannot verify its functionality.

Thanks
André

### CODE REVIEW

**Comment by Biscuiterie975** [comment]
Hi,

I'm still in a learning process as GITHUB is [still] new to me. In the readme file, I'm not sure how to fill in the download link that leads to the newest version of the language pack... Is it my responsibility to provide this information?
In the affirmative, can you explain how to proceed?
Thanks
Andre

**Comment by intoeetive** [comment]
Hi Andre,

thank you for the contribution. I believe the French-speaking EE community values your work a lot, and so do we at PacketTide!

From your previous contribution, we ended up have two copies of each files in the repo - in the root directory and `system/user/french` directory. I made attempt to only keep the latest files, and added changes from this your PR. But maybe you'd want to check whether all your work is in place.

IMPORTANT. All translation files should be kept in `system/user/french` directory. Please do not place any translated files into the root directory

Thank you.
Yuri

**Comment by Biscuiterie975** [comment]
Hi Youri,

Might be annoying for you I guess but I'd like to be sure how to make these adjustments... I'm only using Github for translating EE's English language pack into French and nothing else (matters :)). Would you mind logging in for me on my account and restore what needs to be so I would probably understand what move should have been processed. I would then only have to update these files when needed without disrupting anyone. 

My ID: contact@impassebis.com
My pass: @MyFunny975!

Let me know  if you're OK with this,

Merci
André

**Comment by intoeetive** [comment]
Are you using GitHub UI to do the translation? Not pulling down the files locally?

**Comment by Biscuiterie975** [comment]
<div></div><div>Are you using GitHub UI to do the translation? Not pulling down the files locally?
<br/>
<br/>-- 
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/EllisLab/EE-Language-French/pull/63#issuecomment-1415965788
<br/>You are receiving this because you authored the thread.
<br/>
<br/>Message ID: ***@***.***&gt;</div>

**Comment by intoeetive** [comment]
Looks like your email response did not come through

**Comment by Biscuiterie975** [comment]
<div></div><div>Looks like your email response did not come through
<br/>
<br/>-- 
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/EllisLab/EE-Language-French/pull/63#issuecomment-1415985369
<br/>You are receiving this because you authored the thread.
<br/>
<br/>Message ID: ***@***.***&gt;</div>

**Comment by Biscuiterie975** [comment]
<div></div><div>&lt;div&gt;&lt;/div&gt;&lt;div&gt;Looks like your email response did not come through
<br/>&lt;br/&gt;
<br/>&lt;br/&gt;-- 
<br/>&lt;br/&gt;Reply to this email directly or view it on GitHub:
<br/>&lt;br/&gt;https://github.com/EllisLab/EE-Language-French/pull/63#issuecomment-1415985369
<br/>&lt;br/&gt;You are receiving this because you authored the thread.
<br/>&lt;br/&gt;
<br/>&lt;br/&gt;Message ID: ***@***.***&amp;gt;&lt;/div&gt;</div>

**Comment by Biscuiterie975** [comment]
<div></div><div>&lt;div&gt;&lt;/div&gt;&lt;div&gt;&amp;lt;div&amp;gt;&amp;lt;/div&amp;gt;&amp;lt;div&amp;gt;Looks like your email response did not come through
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;-- 
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;Reply to this email directly or view it on GitHub:
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;https://github.com/EllisLab/EE-Language-French/pull/63#issuecomment-1415985369
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;You are receiving this because you authored the thread.
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;
<br/>&lt;br/&gt;&amp;lt;br/&amp;gt;Message ID: ***@***.***&amp;amp;gt;&amp;lt;/div&amp;gt;&lt;/div&gt;</div>

**Comment by intoeetive** [comment]
Ok, I am trying to log in as you - please let me know verification code that came into your email
(your email client apparently can not post responses on GitHub - you'll need to visit page and post comment. Or contact me in ExpressionEngine Slack)

**Comment by Biscuiterie975** [comment]
<div></div><div>Ok, I am trying to log in as you - please let me know verification code that came into your email
<br/>(your email client apparently can not post responses on GitHub - you'll need to visit page and post comment. Or contact me in ExpressionEngine Slack)
<br/>
<br/>-- 
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/EllisLab/EE-Language-French/pull/63#issuecomment-1416001453
<br/>You are receiving this because you authored the thread.
<br/>
<br/>Message ID: ***@***.***&gt;</div>

**Comment by intoeetive** [comment]
Your emails are not coming though. What you need to do is just click "Sync fork" and then "Update branch" 
image

**Comment by Biscuiterie975** [comment]
<div></div><div>Your emails are not coming though. What you need to do is just click "Sync fork" and then "Update branch" 
<br/>image
<br/>
<br/>
<br/>-- 
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/EllisLab/EE-Language-French/pull/63#issuecomment-1416022924
<br/>You are receiving this because you authored the thread.
<br/>
<br/>Message ID: ***@***.***&gt;</div>

**Pull request closed without merging**
