### PR TITLE
6.3.5

### PR DESCRIPTION
**Pull request by Biscuiterie975**

### CODE REVIEW

**Comment by Biscuiterie975** [comment]
Hi Everyone,
I have translated EE 6.3.4 English language files into French. Would do the same for 6.3.5 if there are changes (I did not find any information on this update ) and EE 7 of course.

**Comment by intoeetive** [comment]
Hi @Biscuiterie975 

Thank you for the contribution!

It does not look like this PR has been done the right way, as it does not include the files other than attaching in zip.
You should for the repo, make the changes, push to your fork and open PR from your fork to 6.x branch in this repo
(but if that sounds too difficult, we could just do that for you)

And yes, the translation for EE 7 will also be welcome

**Comment by Biscuiterie975** [comment]
Hi intoeetive

I've just changed very few words in admin_content_lang.php and uploaded the new version which I've called 6.3.5 by the way : hope no changes in language files have been made between 6.3.4 and 6.3.5 since I did not spot any report on this subject. I'm a newly retired French school principal and have been with EE since PMachine :). Would appreciate to collaborate with some other guys :)  like Eric and will certainly commit with EE7+ which I find very promising. Please feel free to correct the repo procedure.

**Comment by intoeetive** [comment]
@Biscuiterie975 

The workflow should be following:
1. first, fork the repo by using "fork" button on top right here on GitHub.
2. clone locally your forked repo (if you have already cloned the original repo - which I think you did - you can add your clone as a remote)
3. Make the changes and commit them to Git. It is best to use new branch for that, which can be based off 6.x
4. Push your commits to your remote forked repo
5. Visit your forked repo on GitHub. You should see the button to submit pull request right on front page, if not - got to Pull Requests tab and click "Create pull request" there
6. Choose `EllisLab/EE-Language-French:6.x` as base for your PR (make sure you pick the right repo, i.e. not your fork but original one) and "compare" should be the branch with your changes.
7. Submit and you should be done

Again, if this all is too difficult I can do that for you, but it's best if you could familiarize yourself with the process as that would simplify process a lot allowing you to make changes quickly

**Comment by intoeetive** [comment]
The `pro` language file was in separate place in EE 7.0.2
It will be moved to same location that the other files in 7.0.3, which we plan to release today or tomorrow

**Comment by Biscuiterie975** [comment]
@intoeetive,

I have translated the new pro language file brought in 7.0.3. That solves my previous remark, thanks. I will read end re-read a million times all these files to make corrections. Should be completely checked over next week-end.

- In 7.0.3, my  jump menu in the Control Panel always opens a dropdown in English despite the fact that all settings are set to French (for my CP as for my Member profile).  My  jump_menu_lang.php file is well set in the French language folder. 
That wasn't the case in 6.3.5. Is there a conflict related to the pro introduction?

-In the Field section of the Control Panel, the dropdown menu showing field types renders these in English which is no big deal to me. These names must be recovered from some core file most likely? Its not an issue but an observation.

- I don't own a pro licence at this stage and I really love the Snow theme . In my case I don't see any Slate theme on display by clicking on my account avatar ? Is it reserved to to the pro licensees ?

**Comment by intoeetive** [comment]
It is likely that your jump menu javascript file is just cached. Try clearing your browser cache; also just restarting the browser should help

The add-on / fieldtype names are not translated

The easiest way to switch the theme is using jump menu. Type 'theme' and you'll see the list of choices

**Comment by Biscuiterie975** [comment]
<div></div><div>It is likely that your jump menu javascript file is just cached. Try clearing your browser cache; also just restarting the browser should help
<br/>
<br/>The add-on / fieldtype names are not translated
<br/>
<br/>The easiest way to switch the theme is using jump menu. Type 'theme' and you'll see the list of choices
<br/>
<br/>-- 
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/EllisLab/EE-Language-French/pull/53#issuecomment-1210186906
<br/>You are receiving this because you were mentioned.
<br/>
<br/>Message ID: ***@***.***&gt;</div>

**Comment by robinsowell** [comment]
see 7.x branch

**Pull request closed without merging**
