### PR TITLE
EE 3.3.2 FRENCH - updates

### PR DESCRIPTION
**Pull request by ebeauchamps**
With the OK of Wes BAKER (thanks Wes) I put back the fully translated
moblog_lang.php file instead of the « not so original » file pointing
to the moblog add-on folder.

### CODE REVIEW

**Comment by wesbaker** [comment]
@ebeauchamps could you update your repository from upstream? I can't automatically merge this pull request due to some conflicts.

**Comment by ebeauchamps** [comment]
OK, will do that

**Comment by ebeauchamps** [comment]
Come on...what's still going on?

**Comment by wesbaker** [comment]
Alright, got it. Let me know if it looks alright to you.

**Comment by ebeauchamps** [comment]
Hello Wes.
Looking good to me. I am no GIT GURU but it seems OK. Can you close the issue opened in the repo by someone who was asking for the moblog_lang file?
Thanks
Take care.Emmanuel

Date: Tue, 24 May 2016 09:32:03 -0700

**Pull request merged**
